# Generated by Django 3.2.8 on 2021-11-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='test',
            name='task',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
