# Generated by Django 3.2.8 on 2021-11-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20211116_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='password',
        ),
        migrations.RemoveField(
            model_name='test',
            name='task',
        ),
    ]
