# Generated by Django 3.2.8 on 2021-11-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20211116_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
